### PR TITLE
add note on reuse, update ocp versions and doc link

### PR DESCRIPTION
**Pull request by smccarthy-ie**
@bhardesty I'm reusing this module in the RH Integration Release Notes, with some minor tweaks for the OCP version. The updated doc link works for OCP v4.5 and v4.6.

Please let me know if you have any updates or are happy to merge. Thanks.

### CODE REVIEW

**Comment by oraNod** [comment]
@smccarthy-ie and @bhardesty Should we close this PR?

**Comment by smccarthy-ie** [comment]
Hey @oraNod, Merged the PR now that I have the permissions to merge to this repo :)  Very minor tweaks only for URLs.

**Comment by oraNod** [comment]
@smccarthy-ie Sound. I just noticed the PR had been open for a while so thought I'd comment. Hope you don't mind me butting in a little.

**Comment by smccarthy-ie** [comment]
@oraNod No worries, thanks for reminder :)

**Pull request merged**
